site_name: "MIDAS Python"
site_author: "Sumit Shekhar"

extra_css:
  - stylesheets/extra.css

theme:
  # name: shadcn
  name : material
  favicon: assets/favicon.ico
  logo: assets/midas-logo_White.png
  custom_dir: overrides

  palette: 
    scheme: default
    primary: black
    accent: blue

  font:
    text: Roboto Flex
    code: Fragment Mono
  features:
    - navigation.indexes
    - navigation.instant
    - toc.follow
    - navigation.top
    - search.suggest
    - navigation.path
    - content.code.copy
    - header.autohide
    - toc.follow
    - search.suggest
    - header.autohide
    - announce.dismiss
        

plugins:
  - search # put it first to inject out custom code
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
 - admonition
 - toc:
      toc_depth: 3
 - tables
 - pymdownx.highlight
 - pymdownx.inlinehilite
 - pymdownx.superfences
 - pymdownx.snippets
 - pymdownx.details
 - md_in_html
 - attr_list
 - pymdownx.blocks.caption
     


copyright: "Created by Midas India :  MIDAS CIVIL NX - Python interface"


nav:

  - Introduction: index.md
  - Model: model.md
  - Node: node.md

  - Element:
    - Element: Element/index.md
    - ‎ ‎ ‎ 1D Elements: Element/1D.md
    - ‎ ‎ ‎ 2D Elements: Element/2D.md
    - ‎ ‎ ‎ 3D Elements: Element/3D.md 
    - ‎ ‎ ‎ Stiffness Scale Factor: Element/ElemetScaleFactor.md

  - Section Properties:
    - Section : Section/index.md
    - ‎ ‎ ‎ Standard Section : Section/01_user.md
    - ‎ ‎ ‎ PSC Section: Section/02_psc.md
    - ‎ ‎ ‎ Composite Section : Section/03_composite.md
    - ‎ ‎ ‎ Tapered Group : Section/04_taperedgroup.md
    - Thickness : Section/09_thickness.md

  - Material Properties:
    - Material : Material/index.md

    - ‎ ‎ ‎ Concrete : Material/001concrete.md
    - ‎ ‎ ‎ Steel : Material/002steel.md
    - ‎ ‎ ‎ User-defined : Material/003usermat.md

    - Creep Shrinkage : Material/010creep.md
    - Compressive Strength : Material/011comp.md
    - Time Dependent Link : Material/012tdlink.md  

  - Groups:
    - Groups  : Group/index.md
    - ‎ ‎ ‎ Structure Group : Group/001sg.md
    - ‎ ‎ ‎ Boundary Group : Group/002bg.md
    - ‎ ‎ ‎ Load Group: Group/003lg.md
    - ‎ ‎ ‎ Tendon Group: Group/004tg.md


  - Boundary:
    - Boundary : Boundary/index.md
    - ‎ ‎ ‎ Supports : Boundary/01supports.md
    - ‎ ‎ ‎ Elastic Link: Boundary/02elink.md
    - ‎ ‎ ‎ Rigid Link : Boundary/03rlink.md
    - ‎ ‎ ‎ Point Spring : Boundary/04PointSpring.md
    - ‎ ‎ ‎ Multi Linear Function : Boundary/05MLFC.md

  - Load:
    - Load : Load/index.md
    - ‎ ‎ ‎ Self Weight : Load/000sw.md
    - ‎ ‎ ‎ Nodal Load : Load/001nodal.md
    - ‎ ‎ ‎ Beam Load: Load/002beam.md
    - ‎ ‎ ‎ Load To Mass: Load/003LoadToMass.md
    - ‎ ‎ ‎ Nodal Mass: Load/004NodalMass.md
    - ‎ ‎ ‎ Specified Displacement: Load/005spDisp.md
    - Load Case : Load/case.md
  
  - Tendon :
    - ‎ ‎ ‎ Tendon Property : Tendon/001Property.md
    - ‎ ‎ ‎ Tendon Profile : Tendon/002Profile.md
    - ‎ ‎ ‎ Tendon Prestress : Tendon/003Prestress.md


  - Temperature:
    - Temperature Load: Temperature/index.md
    - ‎ ‎ ‎ System : Temperature/001System.md
    - ‎ ‎ ‎ Element: Temperature/002Element.md
    - ‎ ‎ ‎ Gradient: Temperature/003Gradient.md
    - ‎ ‎ ‎ Nodal: Temperature/004Nodal.md
    - ‎ ‎ ‎ Beam Section: Temperature/005Beamsection.md

  - Moving Load:
    - Moving Load : MovingLoad/index.md
    - ‎ ‎ ‎ Code: MovingLoad/000Code.md
    - ‎ ‎ ‎ Vehicle: MovingLoad/001Vehicle.md
    - ‎ ‎ ‎ Line Lane: MovingLoad/002LineLane.md
    - ‎ ‎ ‎ Case: MovingLoad/003VHCase.md
  
  - Settlement:
    - Settlement : Settlement/index.md
    - ‎ ‎ ‎ Group: Settlement/01Group.md
    - ‎ ‎ ‎ Case: Settlement/02Case.md
  
    
  - Construction Stage:
    - Define Construction Stage: CS/001stage.md
    - Composite Section for CS: CS/002compsec.md
    - TIme Loads for CS: CS/003timeloads.md
    - Creep Coefficient for CS: CS/004creepcoeffcs.md
    - Camber for CS: CS/005cambercs.md
  
  - Analysis Control:
    - Analysis Control : AnalysisControl/index.md
    - ‎ ‎ ‎ Main Control Data: AnalysisControl/01MainControlData.md
    - ‎ ‎ ‎ PDelta: AnalysisControl/02Pdelta.md
    - ‎ ‎ ‎ Buckling: AnalysisControl/03Buckling.md
    - ‎ ‎ ‎ EigenValue: AnalysisControl/04EigenValue.md
    - ‎ ‎ ‎ Settlement: AnalysisControl/05Settlement.md
    - Boundary Change Assignment : AnalysisControl/BoundaryChangeAssignment.md
    

  - Results :
    - ‎ ‎ ‎ Load Combination : Result/01_loadCombination.md
    - ‎ ‎ ‎ Result Table : Result/02_resultTable.md
    - ‎ ‎ ‎ User Defined Table : Result/03_userResultTable.md
    - ‎ ‎ ‎ Table : Result/04_Table.md

  - Utilities : Utilities/index.md

  - Discussion : Comments/index.md


